server:
  port: 8080
  servlet:
    context-path: /CinemaUnderTheJava

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/CinemaUnderTheJava
    username: postgres
    password: postgres
    hikari:
      idle-timeout: 10000
      connectionTimeout: 20000
      minimumIdle: 10
      maximumPoolSize: 20
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  mail:
    host: smtp.poczta.onet.pl
    port: 587
    username: justachievevirtualassistant@onet.pl
    password: ENC(081tlkbH0WW76zNZl+uSuM9nTIrJmQCtpj5zHnHsSHD0QG1m+xWiHQ==)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
            checkserveridentity: true
            trust: smtp.poczta.onet.pl
jasypt:
  encryptor:
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    algorithm: PBEWithMD5AndDES
    password: secretkey

verification:
  link: http://localhost:8080/CinemaUnderTheJava/users/activation?token=

api:
  nbp:
    url: http://api.nbp.pl/api/exchangerates/tables/a?format=json