INSERT INTO film (title, film_duration_in_minutes, category) VALUES
('The Shawshank Redemption', 142, 'DRAMA'),
('The Godfather', 175, 'ACTION'),
('The Dark Knight', 152, 'ACTION'),
('Pulp Fiction', 154, 'ACTION'),
('Schindler''s List', 195, 'THRILLER'),
('Forrest Gump', 142, 'DRAMA'),
('The Lord of the Rings: The Return of the King', 201, 'FANTASY'),
('The Matrix', 136, 'ACTION'),
('Inception', 148, 'ACTION'),
('Fight Club', 139, 'DRAMA'),
('The Silence of the Lambs', 118, 'ACTION'),
('The Godfather: Part II', 202, 'ACTION'),
('The Shawshank Redemption', 142, 'DRAMA'),
('The Dark Knight Rises', 165, 'ACTION'),
('The Lord of the Rings: The Fellowship of the Ring', 178, 'FANTASY'),
('The Lord of the Rings: The Two Towers', 179, 'FANTASY'),
('The Godfather: Part III', 162, 'ACTION'),
('The Matrix Reloaded', 138, 'ACTION'),
('The Matrix Revolutions', 129, 'ACTION'),
('The Shining', 146, 'HORROR'),
('The Pianist', 150, 'THRILLER'),
('The Departed', 151, 'ACTION'),
('Django Unchained', 165, 'DRAMA'),
('The Wolf of Wall Street', 180, 'COMEDY'),
('Inglourious Basterds', 153, 'FANTASY'),
('The Social Network', 120, 'THRILLER'),
('Titanic', 195, 'DRAMA'),
('Braveheart 1', 178, 'THRILLER'),
('Braveheart 2', 178, 'THRILLER'),
('The Revenant', 156, 'FANTASY'),
('Gladiator', 155, 'ACTION'),
('The Green Mile', 189, 'ACTION'),
('Saving Private Ryan', 169, 'DRAMA'),
('The Usual Suspects', 106, 'ACTION'),
('Goodfellas', 146, 'ACTION'),
('The Sixth Sense', 107, 'DRAMA'),
('A Beautiful Mind', 135, 'MYSTERY'),
('The Great Gatsby', 143, 'DRAMA'),
('The Grand Budapest Hotel', 100, 'ACTION'),
('The Big Lebowski', 117, 'COMEDY'),
('Blade Runner', 117, 'MYSTERY'),
('For a Few Dollars More', 132, 'WESTERN'),
('Back to the Future', 116, 'FANTASY'),
('Casablanca', 102, 'DRAMA'),
('2001: A Space Odyssey', 149, 'ROMANCE'),
('The Princess Bride', 98, 'WESTERN'),
('The Terminator', 107, 'ACTION');