INSERT INTO seats (row_number, seat_in_row, status, projection_id)
SELECT
    t1.n AS row_number,
    t2.n AS seat_in_row,
    'AVAILABLE' AS status,
    p.id AS projection_id
FROM
    projection p
    CROSS JOIN
    (SELECT 1 AS n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) t1
    CROSS JOIN
    (SELECT 1 AS n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) t2;
